service: blog-github-actions
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_joke:
    handler: handler.rivr
    events:
      - http:
          path: rivr
          method: get

plugins:
  - serverless-python-requirements
