service: blog-github-actions
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json

functions:
  rivr:
    handler: handler.rivr
    package:
      individulally: true
      patterns: # Specify the directories and files which should be included in the deployment package for this specific function.
        - src/rivr/handler.py
    events:
      - http:
          path: rivr
          method: get

plugins:
  - serverless-python-requirements
